import Container from '@mui/material/Container';
import { styled } from '@mui/material/styles';
import Paper from '@mui/material/Paper';
import Grid from '@mui/material/Grid';
import Typography from '@mui/material/Typography';
import './splash.css';
import '@fontsource/roboto/300.css';
import '@fontsource/roboto/400.css';
import '@fontsource/roboto/500.css';
import '@fontsource/roboto/700.css';
import Button from '@mui/material/Button'
import { createTheme } from '@mui/material/styles';
import GalleryGrid from './GalleryGrid/GalleryGrid';
import { useNavigate } from "react-router-dom";
import ReasonToBe from './ReasonToBe/ReasonToBe';
import { getImageCount } from '../../services/apiLayer';
import React from 'react';


const Item = styled(Paper)(({ theme }) => ({
    backgroundColor: theme.palette.mode === 'dark' ? '#1A2027' : '#fff',
    ...theme.typography.body2,
    padding: theme.spacing(1),
    textAlign: 'center',
    color: theme.palette.text.secondary,
}));

const splashContainer = {
    height: {xs: '500px', md: '400px'},
    borderRadius: '15px',
}

const websiteHook = {
    fontFamily: 'roboto',
    fontWeight: '700',
    textAlign: 'left',
    padding: '20px',
    color: '#000000',
    fontSize: '50px',
    lineHeight: '1'
}

const buttonStyle = {
    "text-align": "center",
    margin: "0 0px",
    mt: 0,
    fontSize: '14px',
    border: '2px solid black',
    float: 'left',
    width: '40%',
    height: '56px',
    display: 'flex'
}

const textFieldStyle = {
    color: 'black',
    float: 'left',
    marginLeft: '20px',
    width: '40%',
    height: '55px',
    display: 'flex'
}

const lightTheme = createTheme({
    palette: {
      mode: 'light',
    },
});

const headerStyle = {
    textAlign: {sm: 'center', md: 'left'},
    width: {xs: '340px', sm: '500px', md: '100%'},
    margin: '0 auto',
    fontWeight: '800',
    fontSize: '36px',
    lineHeight: '1.1',
    marginBottom: '20px'
}

const subheaderStyle = {
    textAlign: {sm: 'center', md: 'left'},
    width: {xs: '100%', sm: '500px', md: '100%'},
    margin: '0 auto',
    fontWeight: '300',
    marginBottom: '20px'
}

const numberOfThumbnailsStyle = {
    "color": 'black',
    "fontWeight": '900',
    'display': 'inline',
    'backgroundColor': '#f5d762',
    'padding': '2px 8px',
    'borderRadius': '10px'
}

const buttonCallToAction = 'get started'
const header = 'Create Eye-Catching Youtube Thumbnails'
const subheader = 'Grow your audience by creating thumbnails generated by a Digital AI that will boost your content for the YouTube Algorithm'

export default function Splash() {
    const [numberOfThumbnailsCreated, setNumberOfThumbnailsCreated] = React.useState('1000');

        React.useEffect(() => {
            async function fetchData() {
            try {
                const imageCount = await getImageCount();
                const calculatedValue = imageCount + 600;
                setNumberOfThumbnailsCreated(calculatedValue.toString());
            } catch (error) {
                console.error('Error:', error);
            }
            }

            fetchData(); // Call the async function within useEffect

            // You can also return a cleanup function if needed
            // return () => {
            //   // Cleanup code here
            // };
        }, []);               
    const navigate = useNavigate();

    const onCTAClick = () => {
        navigate("/generate");
    }

    return (
        <Container sx={{backgroundColor: 'none', margin: {xs: '70px auto', md: '100px auto'}}}>
            <Grid container spacing={2}>
                <Grid item sm={12} md={5} sx={{marginBottom: '30px', width: '100%', margin: '0 auto'}}>
                    <Grid item sm={12}>
                    <Typography variant='h4' sx={headerStyle}>
                        {header}
                    </Typography>
                    <Typography variant='h5' sx={subheaderStyle}>
                        {subheader}
                    </Typography>
                    <Button 
                        className="btn-hover color-1"
                        variant="contained"
                        onClick={onCTAClick}
                        sx={{
                            width: '250px',
                            textAlign: 'center',
                            fontSize: '18px',
                            fontWeight: '600',
                            margin: "0 auto",
                            float: {sm: 'center', md: 'left'},
                            mt: 1,
                            mb: '50px',
                    }}> {buttonCallToAction}
                    </Button>
                    </Grid>
                    <Grid item sm={12}>
                        <ReasonToBe />
                    </Grid>
                </Grid>
                <Grid item sm={12} md={7} sx={{margin: '0 auto'}}>
                    <Container sx={{width: '100%'}}>
                        <Typography sx={{"fontSize": '22px'}}>
                            Over <div style={numberOfThumbnailsStyle}>{numberOfThumbnailsCreated} Thumbnails</div> Created!
                        </Typography>
                        <GalleryGrid />
                    </Container>
                </Grid>
            </Grid>
        </Container>
    )
}